name: Deploy Python App to Azure (OIDC) with Slots and Slot Swap

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'app.zip'
  PYTHON_VERSION: '3.9'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_WEBAPP_NAME:       ${{ secrets.AZURE_WEBAPP_NAME }}
  RESOURCE_GROUP:          ${{ secrets.AZURE_RESOURCE_GROUP }}

defaults:
  run:
    working-directory: '.'

permissions:
  contents: read
  id-token:  write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: css-new-runner2
    outputs:
      secrets-valid: ${{ steps.secrets-valid.outputs.isvalid }}
    steps:
      - uses: actions/checkout@v3

      - id: secrets-valid
        env:
          azure-webapp-name:    ${{ secrets.AZURE_WEBAPP_NAME }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          if [ -z "$azure-webapp-name" ] || [ -z "$azure-subscription-id" ]; then
            echo "isvalid=false" >> $GITHUB_OUTPUT
          else
            echo "isvalid=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-secrets
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    runs-on: css-new-runner2
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python app.py &
          sleep 3
          curl -f http://localhost:8000
          echo "Tests passed!"

      - name: Package application
        run: zip -r app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy-staging:
    needs: [check-secrets, build]
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    runs-on: css-new-runner2

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure Login (OIDC)
        uses: azure/login@v1.5.0
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
      - name: Deploy to Staging Slot
        uses: azure/webapps-deploy@v2
        with:
          app-name:   ${{ env.AZURE_WEBAPP_NAME }}
          slot-name:  staging
          package:    ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      

  approve-and-swap:
    needs: deploy-staging
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    runs-on: css-new-runner2
    environment:
      name: production   # Manual approval triggered here
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net

    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v1.5.0
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Start Production Slot Before Swap
        run: |
          az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}

      - name: Start Staging Slot Before Swap (Required!)
        run: |
          az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --slot staging

      - name: Swap Staging Slot into Production
        run: |
          az webapp deployment slot swap \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --slot staging \
            --target-slot production

      - name: Stop Staging Slot After Swap (Optional)
        run: |
          az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --slot staging

      - name: Start Production Slot After Swap
        run: |
          az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
