name: Deploy Python App to Azure

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  PYTHON_VERSION: '3.9'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

defaults:
  run:
    working-directory: '.'

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-secrets:
    # Use your self-hosted runner that is connected to your private network.
    runs-on: [css-new-runner2]
    outputs:
      secrets-valid: ${{ steps.secrets-valid.outputs.isvalid }}
    steps:
      - uses: actions/checkout@v3
      - id: secrets-valid
        env:
          azure-webapp-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        if: env.azure-webapp-name != '' && env.azure-subscription-id != ''
        run: echo "isvalid=true" >> $GITHUB_OUTPUT

  build:
    runs-on: [css-new-runner2]
    needs: [check-secrets]
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Start the app in the background and test its response.
          python app.py &
          sleep 3
          curl -f http://localhost:8000
          echo "Tests passed!"

      - name: Package application for deployment
        run: zip -r app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: [css-new-runner2]
    needs: [build, check-secrets]
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: app.zip

      - name: Validate deployment
        run: |
          curl -f https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net

